<h2>Editar categoria</h2>

<div class="row">
    <div class="col-sm-6">
        <form action="<?php echo APP_URL."categorias/editar"; ?>" method="POST">

            <input type="hidden" name="id" class="form-control" value="<?php echo $this->categorias["id"]; ?>">
            <label for="nombre">Nombre</label>

            <input type="text" name="nombre" class="form-control" value="<?php echo $this->categorias["nombre"]; ?>">
    </div>

        <br>
        <input type="submit" value="Guardar Tarea">

        </form>
</div>